Profile page and nav bar #12 -- Fixed
hatchways/team-cupcake pull request #22
Opened 2019-11-06 14:29 UTC by dipshojol

2019-11-06 16:04 UTC, aitchslash approved these changes

2019-11-06 17:01 UTC, aeciorc requested changes
A few pointers:

1)
The dashboard route shouldn't actually be named (i.e, its path should be "/"). So the profile, message and discover routes would be accessed like this: "localhost:3000/profile", "localhost:3000/discover", "localhost:3000/messages". 

2)The profile route should be the default, so accessing "localhost:3000" would take them to "localhost:3000/profile" (assuming user is logged in, but you don't need to worry about that for now). You're probably gonna want to use a Switch component: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md

3) I noticed that posts are only displayed if we're on the /follow route. That shouldn't be the case

4) Hitting the "message" and "follow" button shouldn't actually take you to any frontend route. That is, we don't need a "profile/follow" and "profile/message" route. 

5) The MakeAPICall file shouldn't be in the components folder. Move it somewhere else, maybe in the "utils" directory?

6) I'd rather JSS styling was used in this project instead of plain css. Take a look at how @Badr-KH styled the forms (utils/formstyles)

2019-11-07 01:48 UTC, dipshojol commented
Made the changes please check and also please let me know if you want me to make any other correction. for now, i am using css and slowly i am gonna convert them into JSS.

2019-11-07 18:24 UTC, aeciorc commented on client/src/pages/Profile.js
> +                            <NavLink to="/profile/follow" activeClassName="current"><li>Follow</li></NavLink>
These shouldn't be NavLinks. They should be regular buttons that will have an action in the future. So they shouldn't take the user anywhere

2019-11-07 18:25 UTC, aeciorc approved these changes
Just one more thing to fix (see my comments) and then you can merge

2019-11-07 18:26 UTC, aeciorc commented on client/src/Components/Nav.js
> +                    <NavLink className={classes.a} to="/profile" activeClassName="active"><li className={classes.li}>Share music</li></NavLink>
Nice job with activeClassName, I didn't know about that prop. Makes things easier for sure!

2019-11-07 18:37 UTC, aeciorc commented
Can you also make the navbar profile picture a link that points to "/profile" ? I've realized there's currently not link to profile

2019-11-08 00:05 UTC, dipshojol commented
hi @aeciorc, please check

2019-11-08 16:54 UTC, aeciorc commented
Feel free to merge

2019-11-08 16:56 UTC, merged