Get auth from Spotify
hatchways/team-cupcake pull request #45
Opened 2019-11-12 12:09 UTC by aitchslash

App registered through my account
I'll need to get you the keys for your local .env
Adding/changing acceptable callback uri's will need to be updated through my Spotify account
Final callback w/ access token needs to be redirected appropriately
Adding refreshToken to User model currently not working.  I'm unsure whether it needs to be done async or if it's some other bug.

2019-11-12 17:06 UTC, aeciorc commented on server/routes/spotify.js
> +require("dotenv").config();
I don't think you need to add this again

2019-11-12 17:22 UTC, aeciorc requested changes

2019-11-12 17:22 UTC, aeciorc commented on server/routes/spotify.js
> +let username; // expand scope, get at login, use to add refresh token
I'm not sure this is thread-safe, and doesn't seem like a good practice anyway. Maybe try passing is as a query parameter together with the redirect_uri (e.g "http://localhost:3001/spotify/callback?user=${username}", then getting it back on the /callback

2019-11-18 15:02 UTC, Badr-KH approved these changes

2019-11-18 15:08 UTC, aitchslash reviewed
Excellent.  Thanks!

2019-11-18 15:08 UTC, Badr-KH approved these changes

2019-11-18 19:35 UTC, merged